export enum Status {
  ABERTO = "ABERTO",
  EM_ANALISE = "EM_ANALISE",
  APROVADO = "APROVADO",
  REPROVADO = "REPROVADO",
  EM_ANDAMENTO = "EM_ANDAMENTO",
  CONCLUIDO = "CONCLUIDO",
  CANCELADO = "CANCELADO",
}
